/**
 * FastLED Keywords for Monaco Editor
 *
 * Copyright (C) 2021, Uri Shaked
 */

import { fastledColors } from './fastled-colors';

export const dataTypes = [
  'CFastLED',
  'CHSV',
  'CRGB',
  'CRGBArray',
  'LEDS',
  'FastLED',
  'FastPin',
  'FastSPI',
  'FastSPI_LED2',

  'CRGBPalette16',
  'CRGBPalette256',
  'CHSVPalette16',
  'CHSVPalette256',
  'CHSVPalette16',
  'CHSVPalette256',
  'CRGBPalette16',
  'CRGBPalette256',
];

export const fastLEDMethods = [
  'addLeds',
  'setBrightness',
  'getBrightness',
  'show',
  'clear',
  'clearData',
  'showColor',
  'setTemperature',
  'setCorrection',
  'setDither',
  'setMaxPowerInMilliWatts',
  'setMaxPowerInVoltsAndMilliamps',
  'setMaxRefreshRate',
  'countFPS',
  'getFPS',
];

export const methods = [
  ...fastLEDMethods,

  // Noise methods
  'inoise16_raw',
  'inoise8_raw',
  'inoise16',
  'inoise8',
  'fill_2dnoise16',
  'fill_2dnoise8',
  'fill_noise16',
  'fill_noise8',
  'fill_raw_2dnoise16',
  'fill_raw_2dnoise16into8',
  'fill_raw_2dnoise8',
  'fill_raw_noise16into8',
  'fill_raw_noise8',

  // Lib8tion methods
  'qadd8',
  'qadd7',
  'qsub8',
  'add8',
  'sub8',
  'scale8',
  'scale8_video',
  'cleanup_R1',
  'nscale8x3',
  'nscale8x3_video',
  'nscale8x2',
  'nscale8x2_video',
  'scale16by8',
  'scale16by8',
  'scale16',
  'mul8',
  'qmul8',
  'abs8',
  'dim8_raw',
  'dim8_video',
  'dim8_lin',
  'brighten8_raw',
  'brighten8_video',
  'brighten8_lin',
  'random8',
  // 'random16',
  'random8',
  'random8',
  'random16',
  'random16',
  'random16_set_seed',
  'random16_get_seed',
  'random16_add_entropy',
  'sin16_avr',
  'sin16',
  'cos16',
  'sin8',
  'cos8',
  'lerp8by8',
  'lerp16by16',
  'lerp16by8',
  'lerp15by8',
  'lerp15by16',
  'map8',
  'ease8InOutQuad',
  'ease8InOutCubic',
  'ease8InOutApprox',
  'ease8InOutApprox',
  'triwave8',
  'quadwave8',
  'cubicwave8',
  'sqrt16',
  'blend8',
  // 'beatsin8',
  // 'beatsin16',

  // Color util methods
  'blend',
  'nblend',
  'ColorFromPalette',
  'HeatColor',
  'UpscalePalette',
  'blend',
  'fadeLightBy',
  'fadeToBlackBy',
  'fade_raw',
  'fade_video',
  'fill_gradient',
  'fill_gradient_RGB',
  'fill_palette',
  'fill_rainbow',
  'fill_solid',
  'map_data_into_colors_through_palette',
  'nblend',
  'nscale8',
  'nscale8_video',

  // HSV methods
  'hsv2grb_rainbow',
  'hsv2rgb_spectrum',
  'hsv2rgb_raw',
  'fill_solid',
  'fill_rainbow',
];

export const colorConstants = Object.keys(fastledColors).map((color) => `CRGB::${color}`);

export const constants = [
  // Chipsets
  'APA102',
  'APA104',
  'APA106',
  'DMXSERIAL',
  'DMXSIMPLE',
  'DOTSTAR',
  'GE8822',
  'GS1903',
  'GW6205',
  'GW6205B',
  'GW6205_400',
  'LPD1886',
  'LPD1886_8BIT',
  'LPD6803',
  'LPD8806',
  'NEOPIXEL',
  'OCTOWS2811',
  'OCTOWS2811_400',
  'OCTOWS2813',
  'P9813',
  'PIXIE',
  'PL9823',
  'SK6812',
  'SK6822',
  'SK9822',
  'SM16703',
  'SM16716',
  'SMART_MATRIX',
  'TM1803',
  'TM1804',
  'TM1809',
  'TM1812',
  'TM1829',
  'UCS1903',
  'UCS1903B',
  'UCS1904',
  'UCS2903',
  'WS2801',
  'WS2803',
  'WS2811',
  'WS2811_400',
  'WS2812',
  'WS2812B',
  'WS2812SERIAL',
  'WS2813',
  'WS2852',

  // RGB orderings
  'RGB',
  'RBG',
  'GRB',
  'GBR',
  'BRG',
  'BGR',

  // Hue literals
  'HUE_RED',
  'HUE_ORANGE',
  'HUE_YELLOW',
  'HUE_GREEN',
  'HUE_AQUA',
  'HUE_BLUE',
  'HUE_PURPLE',
  'HUE_PINK',

  // Color correction values
  'TypicalSMD5050',
  'TypicalLEDStrip',
  'Typical8mmPixel',
  'TypicalPixelString',
  'UncorrectedColor',
  'Candle',
  'Tungsten40W',
  'Tungsten100W',
  'Halogen',
  'CarbonArc',
  'HighNoonSun',
  'DirectSunlight',
  'OvercastSky',
  'ClearBlueSky',
  'WarmFluorescent',
  'StandardFluorescent',
  'CoolWhiteFluorescent',
  'FullSpectrumFluorescent',
  'GrowLightFluorescent',
  'BlackLightFluorescent',
  'MercuryVapor',
  'SodiumVapor',
  'MetalHalide',
  'HighPressureSodium',
  'UncorrectedTemperature',

  // Color util literals
  'FORWARD_HUES',
  'BACKWARD_HUES',
  'SHORTEST_HUES',
  'LONGEST_HUES',
  'LINEARBLEND',
  'NOBLEND',
];
